from .registration_handler import register_regestration_handlers
from .menu_handler import register_menu_handlers
from .back_button_handler import register_back_button_handlers
from .questionnaire_menu_handler import register_questionnaire_menu_handlers
from .change_questionnaire_menu_handlers import register_change_questionnaire_menu_handlers
from .filters_menu_handler import register_filter_menu_handlers
from .questionnaire_handler import register_questionnaire_handlers
from .support_handler import register_support_handlers